// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Web.Bff.Persistence;

#nullable disable

namespace Web.Bff.Persistence.Migrations
{
    [DbContext(typeof(BffDbContext))]
    [Migration("20261004024144_AddOrderProjection")]
    partial class AddOrderProjection
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("bff")
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Common.Infrastructure.Inbox.InboxMessage", b =>
                {
                    b.Property<Guid>("MessageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Endpoint")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .UseCollation("Latin1_General_BIN2");

                    b.Property<DateTimeOffset>("HandledAt")
                        .HasColumnType("datetimeoffset(7)");

                    b.HasKey("MessageId", "Endpoint");

                    b.HasIndex("HandledAt")
                        .HasDatabaseName("IX_Inbox_HandledAt");

                    b.ToTable("InboxMessages", "bff");
                });

            modelBuilder.Entity("Web.Bff.Persistence.OrderLineRow", b =>
                {
                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("LineNumber")
                        .HasColumnType("int");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(19, 4)
                        .HasColumnType("decimal(19,4)");

                    b.HasKey("OrderId", "LineNumber");

                    b.ToTable("OrderLines", "bff");
                });

            modelBuilder.Entity("Web.Bff.Persistence.OrderRow", b =>
                {
                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("AsOf")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<decimal?>("AuthorisedAmount")
                        .HasPrecision(19, 4)
                        .HasColumnType("decimal(19,4)");

                    b.Property<DateTimeOffset?>("AuthorisedAt")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<string>("CancelOutcome")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<DateTimeOffset?>("CancelledAt")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<DateTimeOffset?>("ConfirmedAt")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<string>("Currency")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<Guid?>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("DeliveredAt")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<DateTimeOffset?>("DispatchedAt")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<DateTimeOffset>("FirstSeenAt")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<string>("PaymentCurrency")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<DateTimeOffset?>("PlacedAt")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<decimal?>("RefundedAmount")
                        .HasPrecision(19, 4)
                        .HasColumnType("decimal(19,4)");

                    b.Property<DateTimeOffset?>("RefundedAt")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<decimal?>("TotalAmount")
                        .HasPrecision(19, 4)
                        .HasColumnType("decimal(19,4)");

                    b.Property<string>("TrackingNumber")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("OrderId");

                    b.HasIndex("CustomerId", "FirstSeenAt", "OrderId")
                        .IsDescending(false, true, true)
                        .HasDatabaseName("IX_Orders_Owned")
                        .HasFilter("[CustomerId] IS NOT NULL");

                    b.ToTable("Orders", "bff", t =>
                        {
                            t.HasCheckConstraint("CK_Orders_Authorisation", "([AuthorisedAt] IS NULL AND [AuthorisedAmount] IS NULL) OR ([AuthorisedAt] IS NOT NULL AND [AuthorisedAmount] IS NOT NULL)");

                            t.HasCheckConstraint("CK_Orders_CancelOutcome", "[CancelOutcome] IN (N'cancelled', N'out_of_stock', N'declined')");

                            t.HasCheckConstraint("CK_Orders_Cancellation", "([CancelledAt] IS NULL AND [CancelOutcome] IS NULL) OR ([CancelledAt] IS NOT NULL AND [CancelOutcome] IS NOT NULL)");

                            t.HasCheckConstraint("CK_Orders_PaymentCurrency", "([PaymentCurrency] IS NULL AND [AuthorisedAmount] IS NULL AND [RefundedAmount] IS NULL) OR ([PaymentCurrency] IS NOT NULL AND ([AuthorisedAmount] IS NOT NULL OR [RefundedAmount] IS NOT NULL))");

                            t.HasCheckConstraint("CK_Orders_Refund", "([RefundedAt] IS NULL AND [RefundedAmount] IS NULL) OR ([RefundedAt] IS NOT NULL AND [RefundedAmount] IS NOT NULL)");

                            t.HasCheckConstraint("CK_Orders_Total", "([Currency] IS NULL AND [TotalAmount] IS NULL) OR ([Currency] IS NOT NULL AND [TotalAmount] IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("Web.Bff.Persistence.ProductRow", b =>
                {
                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTimeOffset>("PublishedAt")
                        .HasColumnType("datetimeoffset(7)");

                    b.HasKey("ProductId");

                    b.ToTable("Products", "bff");
                });

            modelBuilder.Entity("Web.Bff.Persistence.OrderLineRow", b =>
                {
                    b.HasOne("Web.Bff.Persistence.OrderRow", null)
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
