// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Notifications.Infrastructure.Persistence;

#nullable disable

namespace Notifications.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(NotificationsDbContext))]
    [Migration("20261002165413_AddIdempotencyMarkers")]
    partial class AddIdempotencyMarkers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("notifications")
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Common.Infrastructure.Idempotency.IdempotencyMarker", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)")
                        .UseCollation("Latin1_General_BIN2");

                    b.Property<DateTimeOffset>("CommittedAt")
                        .HasColumnType("datetimeoffset(7)");

                    b.HasKey("Key");

                    b.HasIndex("CommittedAt")
                        .HasDatabaseName("IX_Idempotency_CommittedAt");

                    b.ToTable("IdempotencyMarkers", "notifications");
                });

            modelBuilder.Entity("Common.Infrastructure.Inbox.InboxMessage", b =>
                {
                    b.Property<Guid>("MessageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Endpoint")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .UseCollation("Latin1_General_BIN2");

                    b.Property<DateTimeOffset>("HandledAt")
                        .HasColumnType("datetimeoffset(7)");

                    b.HasKey("MessageId", "Endpoint");

                    b.HasIndex("HandledAt")
                        .HasDatabaseName("IX_Inbox_HandledAt");

                    b.ToTable("InboxMessages", "notifications");
                });
#pragma warning restore 612, 618
        }
    }
}
