// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Notifications.Infrastructure.Persistence;

#nullable disable

namespace Notifications.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(NotificationsDbContext))]
    [Migration("20261005101149_AddNotificationCorrelationId")]
    partial class AddNotificationCorrelationId
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("notifications")
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Common.Infrastructure.Idempotency.IdempotencyMarker", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)")
                        .UseCollation("Latin1_General_BIN2");

                    b.Property<DateTimeOffset>("CommittedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset(7)")
                        .HasDefaultValueSql("SYSDATETIMEOFFSET()");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Key");

                    b.HasIndex("CommittedAt")
                        .HasDatabaseName("IX_Idempotency_CommittedAt");

                    b.ToTable("IdempotencyMarkers", "notifications");
                });

            modelBuilder.Entity("Common.Infrastructure.Inbox.InboxMessage", b =>
                {
                    b.Property<Guid>("MessageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Endpoint")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .UseCollation("Latin1_General_BIN2");

                    b.Property<DateTimeOffset>("HandledAt")
                        .HasColumnType("datetimeoffset(7)");

                    b.HasKey("MessageId", "Endpoint");

                    b.HasIndex("HandledAt")
                        .HasDatabaseName("IX_Inbox_HandledAt");

                    b.ToTable("InboxMessages", "notifications");
                });

            modelBuilder.Entity("Notifications.Application.Records.Notification", b =>
                {
                    b.Property<Guid>("NotificationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Attempts")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<Guid?>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Languages")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTimeOffset?>("LockedUntil")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<DateTimeOffset>("NextAttemptAt")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Parameters")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Reason")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTimeOffset?>("SendStartedAt")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("TemplateKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int?>("TemplateVersion")
                        .HasColumnType("int");

                    b.HasKey("NotificationId");

                    b.HasIndex("CompletedAt")
                        .HasDatabaseName("IX_NotificationLog_CompletedAt")
                        .HasFilter("[CompletedAt] IS NOT NULL");

                    b.HasIndex("NextAttemptAt")
                        .HasDatabaseName("IX_NotificationLog_SendClaim")
                        .HasFilter("[Status] = 'Pending'");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("NextAttemptAt"), new[] { "LockedUntil" });

                    b.HasIndex("OrderId")
                        .HasDatabaseName("IX_NotificationLog_PendingOrder")
                        .HasFilter("[Status] = 'Pending'");

                    b.HasIndex("EventId", "TemplateKey")
                        .IsUnique();

                    b.ToTable("NotificationLog", "notifications");
                });

            modelBuilder.Entity("Notifications.Application.Records.OrderRecord", b =>
                {
                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CancelOrigin")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("CancelReason")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTimeOffset?>("CancelledAt")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("datetimeoffset(7)");

                    b.HasKey("OrderId");

                    b.HasIndex("RecordedAt");

                    b.ToTable("OrderRecords", "notifications");
                });

            modelBuilder.Entity("Notifications.Infrastructure.Persistence.ContactRecordRow", b =>
                {
                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTimeOffset>("FetchedAt")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<string>("Locale")
                        .HasMaxLength(35)
                        .IsUnicode(false)
                        .HasColumnType("varchar(35)");

                    b.HasKey("CustomerId");

                    b.HasIndex("FetchedAt");

                    b.ToTable("ContactRecords", "notifications");
                });
#pragma warning restore 612, 618
        }
    }
}
