// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Shipping.Infrastructure.Persistence;

#nullable disable

namespace Shipping.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ShippingDbContext))]
    [Migration("20261007031837_AddOutboxTraceContext")]
    partial class AddOutboxTraceContext
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("shipping")
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Common.Infrastructure.Idempotency.IdempotencyMarker", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)")
                        .UseCollation("Latin1_General_BIN2");

                    b.Property<DateTimeOffset>("CommittedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset(7)")
                        .HasDefaultValueSql("SYSDATETIMEOFFSET()");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Key");

                    b.HasIndex("CommittedAt")
                        .HasDatabaseName("IX_Idempotency_CommittedAt");

                    b.ToTable("IdempotencyMarkers", "shipping");
                });

            modelBuilder.Entity("Common.Infrastructure.Inbox.InboxMessage", b =>
                {
                    b.Property<Guid>("MessageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Endpoint")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .UseCollation("Latin1_General_BIN2");

                    b.Property<DateTimeOffset>("HandledAt")
                        .HasColumnType("datetimeoffset(7)");

                    b.HasKey("MessageId", "Endpoint");

                    b.HasIndex("HandledAt")
                        .HasDatabaseName("IX_Inbox_HandledAt");

                    b.ToTable("InboxMessages", "shipping");
                });

            modelBuilder.Entity("Common.Infrastructure.Outbox.OutboxMessage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("Attempts")
                        .HasColumnType("int");

                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Lane")
                        .IsRequired()
                        .HasMaxLength(16)
                        .IsUnicode(false)
                        .HasColumnType("varchar(16)");

                    b.Property<string>("LastError")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTimeOffset?>("LockedUntil")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<string>("TraceParent")
                        .HasMaxLength(55)
                        .IsUnicode(false)
                        .HasColumnType("varchar(55)");

                    b.Property<string>("TraceState")
                        .HasMaxLength(512)
                        .IsUnicode(false)
                        .HasColumnType("varchar(512)");

                    b.HasKey("Id");

                    b.HasIndex("MessageId")
                        .IsUnique();

                    b.HasIndex("OccurredAt")
                        .HasDatabaseName("IX_Outbox_Unprocessed")
                        .HasFilter("[ProcessedAt] IS NULL");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("OccurredAt"), new[] { "Lane", "Attempts", "LockedUntil" });

                    b.HasIndex("ProcessedAt")
                        .HasDatabaseName("IX_Outbox_Processed")
                        .HasFilter("[ProcessedAt] IS NOT NULL");

                    b.ToTable("OutboxMessages", "shipping");
                });

            modelBuilder.Entity("Shipping.Domain.Shipments.Shipment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Attempts")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("CancellationRefusedAt")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<DateTimeOffset?>("CancellationRequestedAt")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<string>("CarrierReference")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset(7)")
                        .HasDefaultValueSql("SYSDATETIMEOFFSET()");

                    b.Property<DateTimeOffset?>("LockedUntil")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<DateTimeOffset>("NextAttemptAt")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<DateTimeOffset?>("NextPollAt")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("PollAttempts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<DateTimeOffset?>("TerminalAt")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<string>("TrackingNumber")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("UnfulfillableReason")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("RowVersion");

                    b.HasKey("Id");

                    b.HasIndex("NextAttemptAt")
                        .HasDatabaseName("IX_Shipments_FulfilmentClaim")
                        .HasFilter("[Status] IN ('Pending', 'Booked') AND [CancellationRefusedAt] IS NULL");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("NextAttemptAt"), new[] { "Status", "CancellationRequestedAt", "LockedUntil" });

                    b.HasIndex("NextPollAt")
                        .HasDatabaseName("IX_Shipments_TrackingClaim")
                        .HasFilter("[NextPollAt] IS NOT NULL");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("NextPollAt"), new[] { "Status", "LockedUntil" });

                    b.HasIndex("OrderId")
                        .IsUnique();

                    b.ToTable("Shipments", "shipping");
                });

            modelBuilder.Entity("Shipping.Domain.Shipments.TrackingEvent", b =>
                {
                    b.Property<Guid>("ShipmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CarrierEventId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .UseCollation("Latin1_General_BIN2");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.HasKey("ShipmentId", "CarrierEventId");

                    b.ToTable("TrackingEvents", "shipping");
                });

            modelBuilder.Entity("Shipping.Infrastructure.Persistence.DeliveryAddressRow", b =>
                {
                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(2)
                        .IsUnicode(false)
                        .HasColumnType("char(2)")
                        .IsFixedLength();

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("FetchedAt")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<string>("Line1")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Line2")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("OrderId");

                    b.ToTable("DeliveryAddresses", "shipping");
                });

            modelBuilder.Entity("Shipping.Domain.Shipments.TrackingEvent", b =>
                {
                    b.HasOne("Shipping.Domain.Shipments.Shipment", null)
                        .WithMany("TrackingEvents")
                        .HasForeignKey("ShipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Shipping.Domain.Shipments.Shipment", b =>
                {
                    b.Navigation("TrackingEvents");
                });
#pragma warning restore 612, 618
        }
    }
}
